/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from "./routes/__root"
import { Route as IndexRouteImport } from "./routes/index"
import { Route as IncidentsIndexRouteImport } from "./routes/incidents/index"
import { Route as IncidentsCreateRouteImport } from "./routes/incidents/create"
import { Route as IncidentsIncidentIdRouteImport } from "./routes/incidents/$incidentId"

const IndexRoute = IndexRouteImport.update({
  id: "/",
  path: "/",
  getParentRoute: () => rootRouteImport,
} as any)
const IncidentsIndexRoute = IncidentsIndexRouteImport.update({
  id: "/incidents/",
  path: "/incidents/",
  getParentRoute: () => rootRouteImport,
} as any)
const IncidentsCreateRoute = IncidentsCreateRouteImport.update({
  id: "/incidents/create",
  path: "/incidents/create",
  getParentRoute: () => rootRouteImport,
} as any)
const IncidentsIncidentIdRoute = IncidentsIncidentIdRouteImport.update({
  id: "/incidents/$incidentId",
  path: "/incidents/$incidentId",
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  "/": typeof IndexRoute
  "/incidents/$incidentId": typeof IncidentsIncidentIdRoute
  "/incidents/create": typeof IncidentsCreateRoute
  "/incidents/": typeof IncidentsIndexRoute
}
export interface FileRoutesByTo {
  "/": typeof IndexRoute
  "/incidents/$incidentId": typeof IncidentsIncidentIdRoute
  "/incidents/create": typeof IncidentsCreateRoute
  "/incidents": typeof IncidentsIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  "/": typeof IndexRoute
  "/incidents/$incidentId": typeof IncidentsIncidentIdRoute
  "/incidents/create": typeof IncidentsCreateRoute
  "/incidents/": typeof IncidentsIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | "/"
    | "/incidents/$incidentId"
    | "/incidents/create"
    | "/incidents/"
  fileRoutesByTo: FileRoutesByTo
  to: "/" | "/incidents/$incidentId" | "/incidents/create" | "/incidents"
  id:
    | "__root__"
    | "/"
    | "/incidents/$incidentId"
    | "/incidents/create"
    | "/incidents/"
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  IncidentsIncidentIdRoute: typeof IncidentsIncidentIdRoute
  IncidentsCreateRoute: typeof IncidentsCreateRoute
  IncidentsIndexRoute: typeof IncidentsIndexRoute
}

declare module "@tanstack/react-router" {
  interface FileRoutesByPath {
    "/": {
      id: "/"
      path: "/"
      fullPath: "/"
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    "/incidents/": {
      id: "/incidents/"
      path: "/incidents"
      fullPath: "/incidents/"
      preLoaderRoute: typeof IncidentsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    "/incidents/create": {
      id: "/incidents/create"
      path: "/incidents/create"
      fullPath: "/incidents/create"
      preLoaderRoute: typeof IncidentsCreateRouteImport
      parentRoute: typeof rootRouteImport
    }
    "/incidents/$incidentId": {
      id: "/incidents/$incidentId"
      path: "/incidents/$incidentId"
      fullPath: "/incidents/$incidentId"
      preLoaderRoute: typeof IncidentsIncidentIdRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  IncidentsIncidentIdRoute: IncidentsIncidentIdRoute,
  IncidentsCreateRoute: IncidentsCreateRoute,
  IncidentsIndexRoute: IncidentsIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
